apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shovel-heroes-production

nameSuffix: -prod

bases:
  - ../../base

commonLabels:
  environment: production

# Production-specific patches
patches:
  # Higher replicas for production
  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3

  - target:
      kind: Deployment
      name: frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3

  # Higher resource limits for production
  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 2Gi

  - target:
      kind: Deployment
      name: frontend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 512Mi

images:
  - name: BACKEND_ECR_URL
    newTag: prod-IMAGE_TAG
  - name: FRONTEND_ECR_URL
    newTag: prod-IMAGE_TAG
