apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shovel-heroes-dev

nameSuffix: -dev

bases:
  - ../../base

commonLabels:
  environment: dev

# Dev-specific patches
patches:
  # Reduce replicas for dev
  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

  # Lower resource limits for dev
  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

  - target:
      kind: Deployment
      name: frontend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi

images:
  - name: BACKEND_ECR_URL
    newTag: dev-latest
  - name: FRONTEND_ECR_URL
    newTag: dev-latest
